### ISSUE TITLE
Documentation/example enhancements 

### ISSUE THREAD

**Issue by holgerteichgraeber** [YoungFaithful/CapacityExpansion.jl#20]
As I am trying to use CapacityExpansion, I'll make some notes here of things where better examples/documentation would help:

- OptVariable, and how to use get_cep_variables() / get_cep_slack_variables() . It is not intuitively clear how to get the values from the fields. Also, what is SLACK?  I assume it is just LL for every hour?
- should sv["LL"].data and sv["LE"].data be floats instead of array{float}?
- explain that they can be indexed, e.g. : sv["SLACK"]["el",1,1,"germany"]   (this is currently not in the documentation of OptVariable)
- add an example with co2_limit. Mention default in the documentatoin.
- Explain the operations optimization function (that if you pass it config, it automatically takes some arguments. list which ones. In my use case, I got an error when I redefined co2_limit. That should happen and is great. Should just be documented.)
- Mention that Gurobi is much faster than Clp and should be preferred if in an academic setting
- show an example of how to configure gurobi in docs (e.g. outputflag=0)
- run_opt documentation: for each option, state the default
- transmission in run_opt(): Does this include transmission as variables? How do I set fixed transmission infrastructure (existing), but without transmission as a variable?
- in run_opt(): if transmission=true, does that mean I allow transmission as a variable? and if transmission=false, I do not allow transmission as a variable? Does false mean that no energy exchange between different nodes can happen?

**Comment by holgerteichgraeber** [comment]
Another addition for the documentation: What is the unit of LE, is it kg CO2 or t CO2? It just says LCA category unit, but there seems no documentation on what that is for CO2.

**Comment by YoungFaithful** [comment]
Addressed in #28
