### ISSUE TITLE
JuMP v0.20

### ISSUE THREAD

**Issue by holgerteichgraeber** [YoungFaithful/CapacityExpansion.jl#25]
There is a JuMP version 0.20. I am getting compatibility errors when updating packages because it seems fixed to 0.19 by CapacityExpansion. Can we make it 0.19 and upwards?

**Comment by YoungFaithful** [comment]
I'll take care of it. The current problem was that 0.19.2 had a bug and I fixed it for that reason.

**Comment by YoungFaithful** [comment]
Gurobi and Clp not yet working with JuMP 0.20

**Comment by holgerteichgraeber** [comment]
I see, that makes sense. Do you know if there is any plans by the maintainers to get it to work?

**Comment by YoungFaithful** [comment]
I am pretty sure.

**Comment by odow** [comment]
Is there any reason JuMP is still capped at v0.19? People on Discourse had a compatibility issue: https://discourse.julialang.org/t/question-about-jump/50675

**Comment by YoungFaithful** [comment]
It seems that both Clp and Gurobi now work with JUMP 0.20. So I see no reason. I'll change the dependencies.
