### ISSUE TITLE
lost_emission_cost - documentation

### ISSUE THREAD

**Issue by holgerteichgraeber** [YoungFaithful/CapacityExpansion.jl#35]
@YoungFaithful: 
In the documentation, is this a typo?  `should be greater than 1e6`. In my previous modeling, I have this value at 700.

https://youngfaithful.github.io/CapacityExpansion.jl/dev/opt_cep/#Running-the-Capacity-Expansion-Problem-1

> lost_emission_cost: Dictionary with numbers indicating the emission price/kg-emission (should be greater than 1e6), give Inf for no LE (Lost Emissions - a variable for emissions that will exceed the limit in order to provide the demand with the installed capacities)

**Comment by holgerteichgraeber** [comment]
Additionally, how about we add an example similar to `"existing" => ["demand","dispatchable_generation"]` in `infrastructure` for lost load and lost emissions here?

**Comment by holgerteichgraeber** [comment]
Workflow example confirms the above. Copying this here for reference:
`lost_load_cost=Dict{String,Number}("electricity"=>1e6),lost_emission_cost=Dict{String,Number}("CO2"=>700)`

**Comment by YoungFaithful** [comment]
Oh yeah, that is a typo.
I think an additional example is a good idea.

**Comment by holgerteichgraeber** [comment]
closed with #38
