### ISSUE TITLE
CA 14 data

### ISSUE THREAD

**Issue by holgerteichgraeber** [YoungFaithful/CapacityExpansion.jl#49]
When I am running the optimization with CA 14 data, I am getting the following error: 
```
ERROR: LoadError: KeyError: key "solar-MX" not found
```
I see that TS/solar.csv does not have a column MX. Is there another file that should be used for CA14?

**Comment by YoungFaithful** [comment]
Interesting, it seems like nodes still includes Mexico. I'll check on it.

**Comment by YoungFaithful** [comment]
Which branch are you currently running?

**Comment by holgerteichgraeber** [comment]
It's on the branch fixed_SOC https://github.com/YoungFaithful/CapacityExpansion.jl/tree/fixed_SOC , which is basically an evolution of master.

data is CA_14_fixedbattransm4 --> should be the same as CA_14 for the purpose of nodes.

**Comment by YoungFaithful** [comment]
There must have been a mistake in copying the data: the [`nodes.csv`](https://github.com/YoungFaithful/CapacityExpansion.jl/blob/fixed_SOC/data/CA_14_fixedbattransm4/nodes.csv) still contains a row `MX` in `CA_14_fixedbattransm4` on branch `fixed_SOC` - the `nodes.csv` should only contain nodes and regions within California like in the branch `master`

**Comment by holgerteichgraeber** [comment]
Thanks, that makes sense, updated the files and it works now.
