### ISSUE TITLE
32bit Numbers incompatible

### ISSUE THREAD

**Issue by YoungFaithful** [YoungFaithful/CapacityExpansion.jl#9]
explicit `Int64` and `Float64` statements lead to Errors on 32bit systems

**Comment by holgerteichgraeber** [comment]
@YoungFaithful do we need to reopen this one as well or was the AbstractFloat issue only in ClustForOpt?

**Comment by YoungFaithful** [comment]
We could, however it does not produce a bug and we could just leave it in dev for the time being.

**Comment by holgerteichgraeber** [comment]
Maybe we could put it in master, I don't know when we merge dev for the next time and it seemed to me that AbstractFloat may lead to memory and runtime issues: https://stackoverflow.com/questions/44729392/generic-float-type-in-julia-language
